### ISSUE TITLE
Finalize replacement of Zend CodeGenerator with Laminas CodeGenerator

### ISSUE THREAD

**Issue by beberlei** [FriendsOfPHP/proxy-manager-lts#11]
There is still code in the library that triggers `class_exists(\Zend\CodeGenerator\ClassGenerator)` for an unclear reason, maybe to make the `laminas/laminas-zendframework-bridge` happy that is transisently loaded via `laminas/laminas-eventmanager` even though it already uses `Laminas` use statements everywhere.

This `laminas-zendframework-bridge` introduces a heavy autoloader as documented here https://github.com/laminas/laminas-zendframework-bridge/issues/83 and this library should make sure to avoid this trap by lobbying this dependency be removed from `laminas/laminas-eventmanager` https://github.com/laminas/laminas-eventmanager/issues/21 and remove the `class_exists` calls.

**Comment by nicolas-grekas** [comment]
IIRC, the call is here to ensure legacy and new names are `class_alias()`'ed properly, so that no BC break occurs when the legacy type is used as a type hint.
I too would be really happy to drop this autoloader.
Why does that call block?

**Comment by beberlei** [comment]
I believe this issue can be closed since `laminas/laminas-code` removed the dependency that leads to the laminas-zendframework-bridge being installed in their 4.4.0 release. This removed the performance bottleneck for us.
