### ISSUE TITLE
proxy-manager-lts can not be installed on php 8.1

### ISSUE THREAD

**Issue by goetas** [FriendsOfPHP/proxy-manager-lts#12]
Hi, we tried to enable the latest proxy-manager-lts  on php 8.1 but we get this error

https://github.com/doctrine/migrations/runs/3643678725?check_suite_focus=true

**Comment by nicolas-grekas** [comment]
That's because no versions of laminas/code with php 8.1 support have been tagged yet, isn't it?
You have to allow the `@dev` version for now.

**Comment by goetas** [comment]
Thanks, did not realize that!

**Comment by goetas** [comment]
it seems that the upcoming `4.4` release will support php 8.1 (https://github.com/laminas/laminas-code/blob/b9e5b989738ab61862265d532e563b715fe5105b/composer.json#L12)

**Comment by garciasdos** [comment]
@nicolas-grekas I see laminas-code just released the 4.5.0 version, with PHP 8.1 compatibility. So we can update the proxy-manager-lts dependencies as well! 😄

**Comment by nicolas-grekas** [comment]
Awesome news!
This package already allows v4.5 do there's nothing to do here.
