### ISSUE TITLE
proxy-manager-lts requires laminas-code which cannot cover php from 7.2 to 8.0

### ISSUE THREAD

**Issue by matks** [FriendsOfPHP/proxy-manager-lts#13]
Hello everyone,

First of all thank you for the great work on this repository. Long term support for old PHP versions is very precious and happens thanks to your hard work.

At [prestashop](https://github.com/prestashop/prestashop) we are trying provide a wide range of PHP versions for our next version, which would be php7.2 to php8.0 .

Although php versions prior to 7.4 are not maintained anymore, in the CMS ecosystem php versions can be slow to upgrade.

Moreover if someone is running a PrestaShop version on php7.2 today and wants to upgrade to the latest version tomorrow, it's very useful for her/him to be able to 1) upgrade the software ; and it runs on 7.2 ; 2) verify everything seems all right 3) upgrade php version. If we drop php7.2 compatibility, this cannot happen and make the upgrade path harder.

proxy-manager-lts requires laminas-code which provide
- a 3.4.x branch that supports php7.1^ but AFAIK does not support php8
- a 3.5.x branch that supports php8 but requires php7.3^

So we cannot have a single set of dependencies for proxy-manager-lts that would support both php7.2 and php8.0.

Would it be possible to consider
- accepting pull requests on laminas-code 4.5.x to cover a wider range of php versions, down to php7.2 ?
- or creating a `-tls` package, just like this one, for laminas-code, to aim for the same goal ? that means a new package friendsofphp/laminas-code-lts, we will be happy to contribute to it to achieve this goal

Have a nice day :) I'm open to all ideas and feedback

**Comment by nicolas-grekas** [comment]
Hi, thanks for the kind words.

I'm not sure how we can help here. I feel like the only option would be to fork laminas-code, make it compatible with the target range of PHP versions, and "replace" it in the composer.json of the fork.

That would work I think. I just don't think it's something we would pursue in this organization. Maybe prestashop should make it happen if it wants to?

**Comment by matks** [comment]
> fork laminas-code, make it compatible with the target range of PHP versions, and "replace" it in the composer.json of the fork.

This is what we'll do indeed if you do not wish to host a laminas-code-lts repository on FriendsOfPHP organization.

But before starting this fork and take on the maintenance burden fully on our side, we check whether you would be interested in it.

> I just don't think it's something we would pursue in this organization

Looks like we'll have the full maintenance burden on our shoulders 😄

**Comment by matks** [comment]
Just found an image I quite relate to 😄  

<img width="50%" src="https://pbs.twimg.com/media/E_5mkCRVcA0I5L9?format=jpg&name=large">

(image source: https://twitter.com/davert/status/1440701785996288008)

Large range of PHP compatibility is hard 😅

**Comment by matks** [comment]
I close issue as I think nothing will be done on FriendsOfPHP organization. We will inform you whether we build/maintain a fork of proxy-manager-lts or laminas-code, so if someone has the same issue as we do, he'll be able to use our implementation.

Have a nice day !

**Comment by matks** [comment]
FYI https://github.com/PrestaShop/laminas-code-lts 😄
