### ISSUE TITLE
The url inside the composer.json should be in their secure version?

### ISSUE THREAD

**Issue by S-Tian86** [FriendsOfPHP/proxy-manager-lts#15]
Hi,

I think the url should be written with https;// instead of http://.
https://github.com/FriendsOfPHP/proxy-manager-lts/blob/b6c48150c32e0704c0394301f47a0ec4890cf05a/composer.json#L14-L19
What do you think?
Regards

**Comment by nicolas-grekas** [comment]
Please send a PR to the source:
https://github.com/Ocramius/ProxyManager/blob/2.14.x/composer.json
