### ISSUE TITLE
doctrine/reflection is abandoned

### ISSUE THREAD

**Issue by bruno-ds** [FriendsOfPHP/proxy-manager-lts#25]
Hello,

as [doctrine/reflection](https://github.com/doctrine/reflection) say itself that it is abandoned:
> :warning:  This package is abandoned, consider migrating to alternatives, such as roave/better-reflection. Features that are still useful to Doctrine have been moved to doctrine/persistence :warning: 

Maybe you should either abandon this project or edit the readme to no longer act as a fork and thus not asking to "report issues and submit new features to the origin library."  

:)

**Comment by nicolas-grekas** [comment]
Not sure what you mean, this repo doesn't rely on `doctrine/reflection`... Closing therefor.
