### ISSUE TITLE
laminas/laminas-code version compatibility

### ISSUE THREAD

**Issue by vkywalker** [FriendsOfPHP/proxy-manager-lts#35]
Hello, 
This is not a bug, but a question, why laminas/laminas-code dependency is limited to that?

` "laminas/laminas-code":      "~3.4.1|^4.0",`

There is a incompatibility with 3.5.x?  We are having 3.5.1 in a project. 
Thank you very much.

**Comment by nicolas-grekas** [comment]
This was on purpose, see 4a66e4e0d3279d3bb3722963b4294331fabe15bc 
But I don't remember why exactly.
