### ISSUE TITLE
on v1.0.17 AtomicType.php type mixed cannot be nullable

### ISSUE THREAD

**Issue by BrandonFlude** [FriendsOfPHP/proxy-manager-lts#39]
Seeing the following error on 1.0.17 that I wasn't seeing on 1.0.16. 

`/vendor/laminas/laminas-code/src/Generator/TypeGenerator/AtomicType.php:217 Type "mixed" cannot be nullable`

**Comment by aboks** [comment]
This should be fixed by #38.
