### ISSUE TITLE
Change version requirement for laminas/laminas-code

### ISSUE THREAD

**Issue by dbrumann** [FriendsOfPHP/proxy-manager-lts#6]
Right now the composer.json has the following requirement:

```
"laminas/laminas-code": "~3.4.1|^4.0"
```

This constraint won't allow version `3.5.x`. This has the downside that it is not possible to support 7.3, 7.4. and 8.0 at once. For reference:

| laminas-code | require |
| --- | --- |
| `3.4.*` | `php: ^7.1` |
| `3.5.*` | `php: ^7.3 \|\| ~8.0.0` |
| `4.0.*` | `php: ^7.4 \|\| ~8.0.0` |

As far as I can tell, it doesn't make sense to take this upstream as the version support is explicitly why this package exists. Would it make sense to change the requirement in the composer.json to support 3.5 as well?

**Comment by nicolas-grekas** [comment]
:facepalm: pr welcome
