### ISSUE TITLE
Allow symfony/filesystem earlier than 4.4.17

### ISSUE THREAD

**Issue by sp-jose-herrero** [FriendsOfPHP/proxy-manager-lts#8]
Requirements have a dependency with an especific version of `symfony/filesystem >= 4.4.17`, this avoids installation if using earlier versions of Symfony.
I see this library is used just to dump code to disk, something that was present on earlier versions of `symfony/filesystem`, I have forked the project and tried `symfony/filesystem:^3.4` to be exact 3.4.47 and it works fine, there is some reason to require '>= 4.4.17`?

**Comment by nicolas-grekas** [comment]
v4.4.17 contains https://github.com/symfony/symfony/pull/39059, which is needed to pass a test in this repo.
If you're up to working on a way to skip this test when a previous version is installed, I'm open to a PR.
Note that 3.4 is EOLed, so that you'd better upgrade instead ;)

**Comment by nicolas-grekas** [comment]
Closing as explained, feel free to submit a PR if you'd like.
